### ISSUE TITLE
Missing linux/limits.h 

### ISSUE THREAD

**Issue by ilgrandeanonimo** [maksimKorzh/msmd-linux#1]
Raspberry Pi 4B 8GB RAM, Raspbian (debian 11)

instead of ln -a ../include sysroot/usr/include I used ln -a sysroot/include sysroot/usr/include (same thing for lib)
My "sysroot" Folder Tree:
[Pastebin](https://pastebin.com/raw/XKwGwusQ)
https://pastebin.com/raw/XKwGwusQ

**Comment by maksimKorzh** [comment]
Great you've found the solution. I was cheating by using my Linux Mint's headers from **/usr/include**.
Since the video you've watched I made some updates and provided automated scripts and added
wifi firmware for Atheros WIFIs. I've recompiled the kernel but didn't yet update the ISO.

As for headers and libraries needed to compile busybox - yeah, that's the pain. It works if I use headers
from the latest Linux Mint but with earlier versions it doesn't work on my side as well (can't compile on old laptop).
If you're on Debian you might have completely different set of headers.

Generally if any headers are missing they could be downloaded from internet.
The proper way of doing things is obviously to provide the build toolchain that would
resolve all the dependencies automatically regardless of host system.

The only excuse I have - I was doing this for myself and when it worked I just made a video
without thinking much of how to recreate the steps on a different host system.

I was partially consulting Minimal Linux Live project's build scripts as a reference, there they
suggest to use /include folder from linux kernel sources but not all the headers are present there
as well, so in my case I needed to add some from my host system.

Please let me know if you've managed to compile and run busybox.
When something goes wrong please provide the logs.

Happy linux compiling!

**Comment by ilgrandeanonimo** [comment]
The onliest way that I found is to statically compile busybox

**Comment by maksimKorzh** [comment]
Static compilation has many annoying limitations, that's why I've dropped that.

**Comment by ilgrandeanonimo** [comment]
Fixed!!!!!!!!
but with some warns: gcc: warning: ../../root/lib: linker input file unused because linking not done
After GLIBC installation I executed "make INSTALL_HDR_PATH=/home/paolo/linux/root headers_install" in kernel dir and now  works.

**Comment by maksimKorzh** [comment]
Congrats! So are you now able to boot from iso and obtain IP address if connected to ethernet?

**Comment by ilgrandeanonimo** [comment]
Not yet😅
I have to sleep because is late, I will continue tomorrow when I am more clear-headed.

**Comment by ilgrandeanonimo** [comment]
PiOS Linker too old, i'm trying from a container with ubuntu 23.04

**Comment by ilgrandeanonimo** [comment]
Solved ✅
